import React, { useEffect } from 'react'
import "./Condition.css"
export const Condition = () => {
    useEffect(() => {
        window.scrollTo(0,0)
          }, [])
            
    return (
        <>
            <section className="artical">
                <div className="container">
                    <div className='terms_heading' style={{ textAlign: "center" }}>
                        <h1>TERMS AND CONDITIONS</h1>

                    </div>
                    <div className="uppersection">
                        <p className='mb-3'>Last updated: November 24,2022</p>
                        <br />
                        <p><strong> Interpretation </strong></p>
                        <p>
                            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        </p>


                    </div>
                    <div className="definition">
                        <strong>Definitions</strong>
                        <p>For the purposes of this Disclaimer:</p>
                        <ul className='ul_defintion'>
                            <li><p><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” “Bullsmart” in this policy) refers to Dados Technologies Private Limited, No.404, 4th Floor, Kamla Charan, CHS Plot No.178, Jawahar Nagar Road, Goregaon West Mumbai Mumbai City MH 400104 IN is an Association of Mutual Funds in India (AMFI) registered entity holding Application Reference Number (ARN) – 245733 and is involved in a business of Mutual Fund Distributor  </p></li>
                            <li><p><strong>Service </strong> refers to the Website or the Application or both.   </p></li>
                            <li><p><strong>You </strong> means the individual accessing the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. </p></li>
                            <li><p><strong>Website </strong>refers to Bullsmart, accessible from <a href="https://www.bullsmart.in">https://www.bullsmart.in  </a></p></li>
                            <li><p><strong>Application </strong>means the software program provided by the Company downloaded by You on any electronic device named BullSmart. </p></li>
                            <li><p><strong>Social Media Platform </strong> means our Youtube channel, Twitter or any other platform solely handled by us.</p></li>
                            <li><p><strong>Forum </strong> means community forum section available on Bullsmart Application. </p></li>
                        </ul>
                    </div>
                    <div className="terms-condition">
                        <p><strong className='underline_term'>Terms and Conditon</strong></p>
                        <p>In these Terms, “you” or “your” means the person accepting these Terms and the company (if any) on whose behalf he/she is acting, and “we,” “us,” “our,” “Stocktwits,” or the “Company” means Dados Technologies Private Limited and its affiliates. The terms describes your rights and responsibilities and form a legally binding agreement Us and You with the respect to your use of the service. By using or accessing any part of the Service, you agree that you are at least eighteen (18) years old and have read, understand, and agree to be bound by all of these terms and conditions. If you do not agree to all of these terms and conditions, you must not use or access the Service. If you are entering into these Terms on behalf of a company, you represent that you have the authority to bind that company to the terms of these Terms. We reserve the right, in our sole discretion, to modify or replace any of the terms or conditions of these Terms at any time. Your continued use of the Service following the posting of any changes to these Terms constitutes your acceptance of those changes and you are responsible for reviewing those terms. Some products or services that become available on the Service may be subject to additional or different terms and conditions, and if those additional terms and conditions conflict with these Terms, those additional terms and conditions will control. </p>
                        <p><strong>PLEASE READ THESE TERMS CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, A DISPUTE RESOLUTION CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED, AND A WAIVER OF RIGHTS TO BRING CLASS ACTION CLAIMS AGAINST US. IF YOU DO NOT AGREE WITH ALL OF THE TERMS OF THE TERMS OF USE AND THE ABOVE ELIGIBILITY REQUIREMENTS, YOU ARE PROHIBITED FROM USING THE SERVICE. </strong></p>

                        <p><strong>1.REGISTRATION OF DATA AND ACCOUNT SECURITY</strong></p>
                        <p>As a condition to using some parts of the Service, you may be required to register an account with Us, select a password and user name and provide other information about your identity, your company or your investments (“Registration Data”). You agree to (a) provide accurate, current and complete Registration Data; (b) maintain the security of your password and user name; (c) maintain and promptly update the Registration Data, and any other information you provide to the Company, to keep it accurate, current and complete; and (d) be fully responsible for all use of your account and for any actions that take place using your account. Except as expressly provided in these Terms, you may only maintain one active account with the Services. </p>
                        <p>You agree and understand that you are responsible for maintaining the confidentiality of your Registration Data. By providing us with your e-mail address, you agree to receive all required notices electronically, including through the Services (such as by displaying links to notices generally on the Site) or to your e-mail address. It is your responsibility to update or change that e-mail address, as appropriate.  </p>
                        <p></p>
                        <p><strong>2.ACCESS TO THE SERVICE </strong></p>
                        <p>Subject to your compliance with these Terms, we grant you a limited, revocable, nonexclusive license to access and use the Service and the Content for your own personal internal use. This license does not include any collection, aggregation, copying, duplication, scraping, display or derivative use of the Service nor any use of data mining, crawlers, robots, spiders, or similar data gathering and extraction tools for any purpose unless expressly permitted by Us in writing. A limited exception is provided to general purpose internet search engines and non-commercial public archives that use such tools to gather information for the sole purpose of displaying hyperlinks to the Service. In order to collect, aggregate, copy, duplicate, scrape, display or make derivative use of the Service or any Content made available via the Service for other purposes (including commercial purposes) not stated herein, you must first obtain a written license from Us. </p>
                        <p></p>
                        <p><strong>3.REGULATORY COMPLIANCE </strong></p>
                        <p>You agree to insure that any information disseminated pursuant to the Service, whether such dissemination is made (a) by you or on your behalf by a person authorized to disseminate information on your behalf or (b) otherwise, in any case, complies with all statutes, rules, regulations, orders or other governmental acts of India.</p>
                        <p></p>
                        <p><strong>3.REGULATORY COMPLIANCE </strong></p>
                        <p>You agree to insure that any information disseminated pursuant to the Service, whether such dissemination is made (a) by you or on your behalf by a person authorized to disseminate information on your behalf or (b) otherwise, in any case, complies with all statutes, rules, regulations, orders or other governmental acts of India. </p>
                        <p></p>

                        <p><strong>4.PAYMENT POLICIES  </strong></p>
                        <p>Our purchase and checkout process from the Application is powered by our third party payment processors (“Payment Processor”). The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Processor, in addition to this Agreement. You agree to pay us, through the Payment Processor, all charges at the prices then in effect for any purchase in accordance with the applicable payment terms. You agree to make payment using the payment method you provide with your Account. We reserve the right to correct, or to instruct our Payment Processor to correct, any errors or mistakes, even if payment has already been requested or received. You are responsible for all taxes, duties, and other governmental assessments associated with your activity in connection with the Service. </p>
                        <p></p>

                        <p><strong>5.SITE CONTENT  </strong></p>
                        <p>You understand that all postings, messages, text, images, video or other materials (“Content”) posted or published on, uploaded to, transmitted through, or linked from, the Service (hereinafter, “post”, “posted” or “published”), whether by, users of the Service (“Users”) or Creators (as defined below), are the sole responsibility of the person or entity from whom such Content originated. You agree that by using the Service, you may be exposed to Content that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. We are not responsible for the conduct, whether online or offline, of any User or Creator. You agree that you bear all risks associated with, the use or posting of any Content, that you may not rely on said Content, and that under no circumstances we will be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted or otherwise made available via the Service. You may not republish, post, transmit or distribute the Content to online bulletin and message boards, blogs, chat rooms, intranets or anywhere else without our consent.  The Creators may take positions inconsistent with the views expressed in their Products or Content. Products available on our platform contain the Creators’ own opinions (and not those of the Company), and none of the information contained therein constitutes a recommendation that any particular security, portfolio of securities, transaction, or investment strategy is suitable for any specific person. You further understand that the Creators will not advise you personally concerning the nature, potential, value or suitability of any particular security, portfolio of securities, transaction, investment strategy or other matter. </p>
                        <p></p>

                        <p><strong>6.USER CONTENT POSTED ON THE SERVICE </strong></p>
                        <p>You are solely responsible for the Content that you post on or through the Service, or otherwise transmit to or share with other Users (collectively, the “User Content”). You shall not (and shall not permit any third party to) create, upload, download, post, submit or otherwise distribute or facilitate distribution of any User Content on or through the Service, that you did not create or have permission to post; infringes any patent, trademark, trade secret, copyright, moral right, right of publicity, right of privacy, or other right of any other person or entity or violates these Terms or any law or contractual duty (see our Notice of Infringement – DMCA policy below); you know is false, misleading, untruthful or inaccurate; defames, libels, ridicules, mocks, disparages, threatens, harass, intimidates or abuses anyone; attempts to impersonate any other party; harvests or otherwise collects information about users without their consent; uses tools which anonymize your internet protocol address (e.g. anonymous proxy) to access the Service; constitutes unauthorized or unsolicited advertising, junk or bulk email or pyramid schemes; includes anyone’s identification documents or sensitive financial information. You acknowledge that We does not pre-screen, endorse or approve User Content, but that we shall have the right (but not the obligation) in its sole discretion to refuse, delete or remove any User Content that is available via the Service, including in connection with violations of the letter or spirit of the Terms or for any other reason. You are solely responsible at your sole cost and expense for creating backup copies and replacing any User Content you post or store on the Service or otherwise provide to the Company. </p>
                        <p>When you post User Content to the Service, you authorize and direct us to make such copies thereof as we deem necessary in order to facilitate the posting and storage of the User Content on the Service. By posting User Content to any part of the Service, you automatically grant, and you represent and warrant that you have the right to grant, to us an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with the right to sublicense) to use, copy, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part) and distribute such User Content, and your name, voice, and/or likeness as contained in your Content, for any purpose, commercial, advertising, or otherwise, on or in connection with the Service or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize of the foregoing. We do not assert any ownership over your User Content; rather, as between us and you, subject to the rights granted to us in these Terms, you retain full ownership of all of your User Content and any intellectual property rights or other proprietary rights associated with your User Content. You also hereby grant each user of the Service a non-exclusive license to access your User Content through the Service, and to use, reproduce, distribute, display and perform such User Content as permitted through the functionality of the Service and under these Terms. </p>
                        <p></p><p></p><p></p>

                        <p>WE ALSO RESERVE THE RIGHT, AT ALL TIMES AND IN OUR SOLE DISCRETION, TO DISCLOSE ANY USER CONTENT AND OTHER RELATED INFORMATION FOR ANY REASON, including without limitation (a) to satisfy any applicable law, regulation, legal process or governmental request; (b) to enforce the terms of the Agreements; (c) to protect our legal rights and remedies; (d) if we, in our reasonable discretion, believe that someone’s health or safety may be threatened; or (e) to report a crime or other offensive behavior. </p>
                        <p></p>
                        <p><strong>7.THIRD- PARTY SERVICES, OTHER WEBSITES AND CONTENT </strong></p>
                        <p>The Company may provide links or access to other websites, apps, products or services provided by third-party service providers (“Third-Party Services”) when you visit the Site or use the Service. Third-Party Services are not reviewed, controlled, examined, sponsored, or endorsed by us and we are not responsible for the information, advertising, products, resources or other material of any Third-Party Services or any link contained in Third-Party Services. The inclusion of any Third-Party Services not imply endorsement of the owner/sponsor of the Third-Party Services or its content by us. Your use of any such Third-Party Services is at your own risk. We make no representations or warranties with respect to Third-Party Services and will not be liable for such Third-Party Services, even when used in conjunction with the Service. We do not endorse or sponsor any products or services provided by third parties that are made available through the Service. In using any Third-Party Services made available via the Service, you must agree to comply with and be bound by the Terms of Service, Privacy Policy, or other terms and conditions of the third-party service providers. We are not responsible for any trading, buy/sell orders or other activity that you conduct or that otherwise happens in connection with any of your brokerage accounts. </p>
                        <p></p>
                        <p><strong>8.ACCOUNT INFORMATION FROM THIRD PARTY SITES  </strong></p>
                        <p>Users may direct us to retrieve their own information maintained by third-parties with which they have customer relationships, maintain accounts or engage in financial transactions (“Account Information”). By submitting information, data, passwords, usernames, PINs, other log-in information, materials and other content to us through the Service, you are granting us a rights to use such information and content for the purpose of providing the Service. We may use and store the content in accordance with this Agreement and our Privacy Policy. You represent and warrant that you are entitled to submit it to us for use for this purpose, without any obligation to pay any fees or be subject to any restrictions or limitations, including any contained in the third party’s terms of service. We works with third parties to access your Account Information. We makes no effort to review the Account Information for any purpose, including but not limited to accuracy, legality or non-infringement. By using the Service, you expressly authorize us to access and store your Account Information maintained by identified third parties, on your behalf as your agent. </p>

                    </div>
                    <div>
                        <p style={{ textAlign: "center" }}><strong className='underline_term'>COMMUNITY GUIDELINES </strong></p>
                        <p>Bullsmart operates the Platform as an Intermediary under the IT Act. This document is published in accordance with the provisions of the Information Technology Act of 2000 read along with its relevant rules including <strong>Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 </strong> and amendments if any. Bullsmart holds no control with respect to the content and does not warrant the correctness, validity or legality of the content. Bullsmart expressly disclaims all warranties and shall not be liable for any violations under civil or criminal law. </p>
                        <p><strong className='underline_term'>Acceptance- </strong>hat the policy shall be the part of terms of services come into effect. The Platform facilitates aggregation of Content from various sources. Bullsmart merely provides access to various types of content as an intermediary. </p>
                        <ul className='ul_defintion'>
                            <li>Bullsmart is not liable for any content uploaded or made accessible on the Platform because it is not its property. </li>
                            <li>You must not access or post content through any unauthorised means, including but not limited to, by using an automated device, script, bot, spider, crawler, or scraper. </li>
                            <li>You agree to post content in good faith only for legal and non-commercial purposes, including education, entertainment, criticism, or spreading information.</li>
                            <li>Don’t utilise illegal methods or upload content on the Platform with malicious intent. </li>
                            <li>Don’t utilise illegal methods or upload content on the Platform with malicious intent.</li>
                            <li>You confirm that the material you post complies with all applicable laws, rules, regulations, policies, guidelines, and/or norms in the nations where it is published, made available to the public, or distributed by Bullsmart. You attest that You have the necessary rights to publish the content on the platform. Bullsmart is under no obligation to post any data or content on the Platform, and it is free to do so in its sole discretion, with or without giving users prior notice. Bullsmart aims to provide readers with a simple way to locate news from publications who regularly create independent and unique content, with a sizable supply of fresh and purposeful content.</li>
                            <li>The content and conduct guidelines assist in ensuring a satisfying user and publishing partner experience. Content should adhere to best practices, such as those outlined in our standards, in order to be eligible to appear on the Platform, and it must not be: </li>
                            <li><strong>Hate Speech and Discrimination –</strong>Show others on the platform respect, empathy, and dignity. On the platform, we support legitimate and well-intentioned expressions of constructive dissent. Any hateful, personal attacks, ad hominem remarks, or uncivil disagreement meant to injure another user or put them through mental or emotional hardship is not permitted. Comments that incite violence, are racially or ethnically offensive, or criticise somebody based on their national origin, sex, gender identity, sexual orientation, religious affiliation, impairments, or diseases are examples of hostile or discriminatory speech. Additionally, we forbid any content that would entice other users to share it. In your profile image or profile header, you are not allowed to use hateful imagery or symbols. Additionally, you are not allowed to change your username, display name, or profile bio in a way that makes it seem as though you are acting abusively, or that could be inferred to be spreading hate or harassing other users. </li>
                            <li><strong>Religiously offensive Content- Regardless </strong>of whether they have the same opinions as you, you must always show respect for other people’s religious faith and ideas. You must not publish anything that offends people’s feelings or disparages their faith or culture. </li>
                            <li><strong>Extremism and terrorism– </strong>On the Platform, you must not make any deadly threats or encourage risky behaviour. In particular, you are forbidden from using the Platform to encourage terrorism, secession, violent acts against people or property, threats to India’s unity, integrity, defence, security, or sovereignty, or insults to other countries. You must not publish any material that supports or incites users to act in support of a terrorist organisation or an anti-national organisation, or that solicits members for, disseminates information for, or advances the goals of such organizations. Additionally, you must not establish networks on the site that incite violence or solicit support or sanction for carrying out violent activities during authorized protests. </li>
                            <li><strong>Graphic and Violent Content- </strong>You are not permitted to threaten another individual with physical violence directly or indirectly through the Platform. This includes any danger of theft, vandalism, unlawful detention, physical harm, mental anguish, or financial loss. In particular, if vulnerable communities or groups are the principal targets or victims, the Platform does not permit its users to publish anything that refers to mass murder, violent events, or specific forms of violence, or that portrays or promotes any such activities. Platform strictly prohibits the promotion of violence in any form, including but not limited to acknowledging incidents that have wounded someone physically or their feelings. You must not upload anything that features torture, injury, mental suffering, death, bodily harm, abduction, kidnapping or other forms of violent content.</li>
                            <li><strong>Child Sexual Abuse Content- </strong>Any sexually explicit or suggestive content involving children or individuals who appear to be minors is prohibited by Bullsmart or blocked. This includes depictions of child sexual abuse, child pornography, and any other material, even fictional material (such as stories or “loli” or anime cartoons), that sexualizes children or those who have the appearance of being children. Bullsmart has zero tolerance for any information, including articles, blogs, graphic posts, and comments, that supports child sexual abuse. Any users who intend to victimise, endanger, or otherwise exploit minors by publishing content on child sexual abuse. </li>
                            <li><strong>Cyberbullying and Harassment– </strong>Users should feel safe to express themselves so we don’t allow bullying or harassment content. We intend to give our users the freedom to express their opinions without fear of emotional or psychological distress. We also do not tolerate abusive content or behaviour on our platform.</li>
                            <li><strong>Privacy invasion–</strong>Bullsmart anticipates that its users will respect the privacy of others. You must not share, publish, or promote the publication of any other person’s personal information or information that violates their privacy settings. without their explicit consent and authorization. We forbid threatening to do so by disclosing personal information. </li>
                            <li><strong>Sensitive media information including graphic and explicit material–</strong>xtremely graphic information is not permitted, nor is sharing violent or explicit material in comments, articles, or photographs. It is prohibited to display sexual violence or assault in the media. Bullsmart does not permit any content, including non-consensual sexual acts, intimate images of such acts, or adult sexual solicitation. </li>
                            <li><strong>Misinformation and Fake News–</strong>We don’t permit audio, video, or image information that has been altered to deceive, defraud, or mislead by portraying acts or events that can be proven to have not actually occurred. This includes situations when such content might provide a reasonable person a fundamentally incorrect idea or perception, giving rise to the possibility of major harm to persons or organisations, or seriously undermining participation or trust in political or civic processes. Users must refrain from generating traffic or increasing their following, views, comments, or shares using artificial or manipulative means. </li>
                            <li><strong>Self-harm and suicide– </strong>On the platform, there can be no content that promotes self-harm, suicide, or other risky behaviours. Posts that even give instructions on how to commit suicide or self-harm in any way are not allowed, nor is content that shows self-harm, glorifies self-injury or suicide. Content that helps those going through serious problems is permitted. </li>
                            <li><strong>Identity theft and impersonation– </strong>You may not pretend to be someone else, a company, or another entity in order to mislead consumers about the source of the information. You are invited to voluntarily verify your identity to make sure that all the information you have supplied is true and does not, in any way, amount to misrepresentation. </li>
                            <li><strong>Profanity and vulgar language:</strong>We do not permit anything that is overly gory or disturbing, particularly material that encourages or glorifies horrific violence or suffering. For specific situations, such as content that is newsworthy or intended to raise awareness about issues, we do accept exceptions. We prohibit the account and, if there is a real risk of violence or a harm to the public’s safety, we cooperate with the proper legal authorities as required and as appropriate.</li>
                            <li><strong>Malicious Programmes–</strong>Do not knowingly post or distribute material that is untrue, misleading, or inaccurate but may be taken as fact. We have a strict no-tolerance policy for altered or morphing media, including videos and edited images. We do not support material that could harm citizen-centric procedures. Additionally, we forbid any content that might tamper with the outcome of political elections. To the greatest extent practicable, you must ensure that the material you publish on the Platform is true and comes from a reputable, verifiable source. </li>
                            <li><strong>Regulated and illegal activities–</strong>We forbid the use, trade, sale, and advertising of some restricted commodities as well as the portrayal or encouragement of illegal activity. Even if the activities or items in question are lawful in the jurisdiction in which the content was posted, certain content may be removed if it refers to things that are prohibited or controlled in most of the region or the world. For information that benefits the public, such as scholarly, artistic, and journalistic materials, we permit exceptions. </li>
                            <li>Please ensure that the content posed by You is not illegal, immoral or unethical. </li>
                            <li>Any content promoting or selling weapons, firearms, explosives, illegal goods or services, regulated goods, drugs, controlled substances, soliciting or selling sexual services is not allowed on the platform and is strictly prohibited.</li>
                            <li>Content that is related to or encourages money laundering or gambelling are strictly prohibited. </li>
                            <li>Content containing computer viruses, malware, or any other kind of computer code aimed at restricting the functionality of a computer resource is not allowed to be uploaded on the Platform. </li>


                        </ul>

                        <br className='display_br' /><br className='display_br' />
                        <div>
                            <p><strong>1.Intellectual Property</strong></p>
                            <p>You acknowledge, confirm and agree that all intellectual property rights in the Content You post vests with You or You have a valid license to post, display, reproduce, make copies, broadcast, communicate to the public such Content on the Platform. </p>
                            <p>You acknowledge, confirm and agree that all intellectual property rights in the Platform, whether registered or unregistered, including but not limited to its software, interface, webpages, database, name and logo vest in Bullsmart. You shall not claim any right in any of the aforementioned forms of intellectual property.</p>
                            <p>You own the content posed by You. Bullsmart owns all the rights in the Platform.</p>
                            <p>When You post content on the Platform, You grant Bullsmart a non-exclusive, perpetual, worldwide, transferable, irrevocable, royalty-free, unlimited license to use, commercially use, cache, store, publish, display, distribute, and store such Content, including underlying works in the content, posted by You. You agree, understand and confirm that You are liable to pay any license fee, royalty, or any other consideration applicable to the content posted by You. </p>
                            <p>You grant Bullsmart a right to use the content posed by You on the Platform. </p>
                            <p>Other than as expressly set forth in this Policy, You shall not copy, modify, publish, transmit, upload, participate in the transfer or sale of, reproduce (except as provided in this Section), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.</p>
                            <p>Do not use any content posted on the Platform for unauthorized purposes.</p>
                            <p>If You remove any Content from the Platform or terminate Your use of the Platform, Bullsmart may keep and use Your Content on its sole discretion and for any lawful purpose. Bullsmart and its users may retain and continue to use, store, any of Your Content even after the date of termination of Your use. </p>
                            <p>BULLSMART retains the right to use content even after You remove it from the Platform. </p>

                            <p><strong>2.Representations and Warranties </strong></p>
                            <p>You represent, covenant and warrant that the content posted by You does not violate any term of this Policy or any law in force in the territory in which You are posting the content or any law in force in the territory in which content can be displayed, broadcasted, published, used, communicated to public, reproduced or copied.</p>
                            <p>You further represent, covenant and warrant that You own or have a valid license to post the content, including underlying works in the content, on the platform and fulfil Your obligations under this Policy.</p>
                            <p>You confirm that the You post is legal and You have a right to post it.</p>
                            <p>Bullsmart makes no warranties under this Policy. And Bullsmart expressly disclaims all warranties, expressed or implied, including but not limited to: </p>
                            <ul className='ul_defintion'>
                                <li>express or implied warranties of merchantability, fitness for a particular purpose and non-infringement with respect to the Platform(s) or any other aspect; </li>
                                <li>Warranties with respect to the any and all content;</li>
                                <li>warranties as to the quality or performance of the Platform(s), services, technology including but not limited to the availability of any advertisement; and</li>
                                <li>warranties that the Platform(s) and/or the services offered by it will be uninterrupted, timely, or error-free. </li>
                            </ul>
                            <p>Bullsmart makes no warranties with respect to the Platform. </p>
                            <p><strong>3.Indemnity </strong></p>
                            <p>You will indemnify and hold Bullsmart and its affiliates, business partners, and their directors, officers and employees, harmless, including costs and attorneys’ fees, harmless from any claim or demand made by any third party arising out of or in connection with the Content posted by You, any violation of this policy by You, or any other illegal act done by You. </p>
                            <p>If Bullsmart is sued because of anything You do on the Platform, you have to pay the costs. </p>
                            <p>To the maximum extent permitted by law, Bullsmart and/or its affiliates shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) Your access to or use of or inability to access or use the platform; (b) any conduct or content of any third party on the platform, including without limitation, any defamatory, offensive or illegal conduct of other users or third parties; or (c) unauthorized access, use or alteration of Your transmissions or content. In no event shall Bullsmart ‘s aggregate liability for all claims relating to the platform exceeds ₹5000/- (Rupees five thousand only). </p>

                            <p><strong>4.Our liability is limited. </strong></p>
                            <p>This limitation of liability is part of the basis of the bargain between You and Bullsmart and shall apply to all claims of liability (e.g. warranty, tort, negligence, contract, law) and even if Bullsmart or its affiliates have been told of the possibility of any such damage, and even if these remedies fail their essential purpose.</p>

                            <p><strong>5.Acceptance of this Policy</strong></p>
                            <p>By downloading, installing, and accessing/using the Platform and Services, You are signifying Your acceptance of this Privacy Policy. If You do not agree to this Privacy Policy, You shall not download, install, access or use the Platform and Services. Your continued Access or Use of the Platform and Services following the posting of changes to this Privacy Policy will be deemed to be the acceptance of such changes.</p>


                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
