import React, { useEffect } from 'react'
import "./Terms.css"

export const Terms = () => {
    useEffect(() => {
    window.scrollTo(0,0)
      }, [])
    return (
        <>
    <section className="artical">
            <div className="container">                
                <div className='terms_heading' style={{ textAlign: "center" }}>
                    <h1>PRIVACY POLICY</h1>
                    
                </div>
                    <div className="uppersection">
                        <p className='mb-3'>Last updated: November 24,2022</p>
                        <br />
                        <p>
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of any natural or legal person who has visited the Bullsmart website/platform and/or the mobile application, and/or who may or may not have further agreed to initiate the process of opening an account with Bullsmart shall come under the purview of the scope of this Privacy Policy. Bullsmart shall at all times follow all such rules prescribed under the Information Technology Act, 2000, and rules & procedural guidelines set by the Securities Exchange Board of India (“SEBI”) and/or any of its regulated entities/intermediaries that Bullsmart is a member. Bullsmart is a member of The Association of Mutual Fund (AMFI) having its Application Reference Number (ARN) 245733.  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. 


                        </p>

                        <p>Bullsmart encourages You to carefully review the privacy policies of all Third-Party Services You access through the Platform. </p>
                    </div>
                    <div className="definition">
                        <strong>Definitions</strong>
                        <p>For the purposes of this Privacy Policy:</p>
                        <p><strong>Account  </strong>   means a unique account created for You to access our Service or parts of our Service.</p>
                        <p><strong>Company  </strong>   (referred to as either “the Company”, “We”, “Us” or “Our” “Bullsmart” in this Agreement) refers to Dados Technologies Private Limited, No.404, 4th Floor, Kamla Charan, CHS Plot No.178, Jawahar Nagar Road, Goregaon West Mumbai Mumbai City MH 400104.</p>
                        <p><strong>Cookies  </strong>  are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                        <p><strong>Country  </strong>  refers to: India</p>
                        <p><strong>Device   </strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                        <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. </p>
                        <p><strong>Service</strong> refers to the Website.</p>
                    </div>
                    <div className="service-provider">
                        <p> <strong>Service Provider  </strong>  means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                        <p> <strong>Usage Data  </strong>  refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). </p>
                        <p> <strong>Website  </strong>  refers to Bullsmart, accessible from https://www.Bullsmart.in </p>
                        <p><strong>You  </strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                    </div>
                    <div className="bullinfo">
                        <strong className="mb-4">What information may be collected by Bullsmart</strong>
                        <p className="mt-2">Bullsmart might collect your name, email, mobile number, phone number, street, city, state, pincode, country and IP address. We may collect demographic information about you, events you like, events you intend to participate in, which advertisement you find most useful, or any other information provided by your during the use of our website or mobile application (APP). We might collect this as a part of a survey also. We may collect information from Users at various stages from registration on the Platform by the Users to submission of content by the Users or while the User is accessing/using Services. You may choose to not provide the information if You do not wish to use the Platform and/or Services. </p>
                        <strong>We collect information in different ways.</strong>
                        <p className='mt-2'>We collect information directly from you. We collect information directly from you when you use our website or mobile APP. We also collect information if you post a comment on our websites or ask us a question through phone or email or any other platform provided by us</p>
                    </div>
                    <div className="thirdparty">
                    <strong>Third party sites</strong>
                        <p>If you click on one of the links to third party websites, you may be taken to websites we do not control. This policy does not apply to the privacy practices of those websites. Read the privacy policy of other websites carefully. We are not responsible for these third-party websites.</p>
                        <p>Mere presence of the link or its listing on this website or mobile App should not be assumed as endorsement of any kind. We cannot guarantee that these links will work all the time and we have no control over availability of linked pages </p>
                        <p>Part of the Platform or the Services may contain advertising information or promotion material, or other material submitted to the Bullsmart by third parties. Responsibility for ensuring that material submitted for inclusion on the platform complies with applicable law is exclusively on the party providing the information/material.</p>
                        <p>Your correspondence or business dealings with, or participation in promotions of advertisers including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. Before relying on any advertising material, you should independently verify its relevance for your purpose and should obtain appropriate professional advice. We shall not be responsible nor liable for any loss or claim that you may have against an advertiser or any consequential damages arising on account of your relying on the contents of the advertisement. </p>
                        <p>We do not sell or share any personally identifiable information volunteered on the Portal Website to any third party (public/private). Generally accepted best practices shall be user to protect any information provided to this website to protect from loss, misuse, unauthorized access or disclosure, alteration, or destruction. </p>
                        <p>However, at times, Bullsmart may be required by law or litigation to disclose personal information about the Users. Bullsmart may also disclose information about the Users if Bullsmart determines that for national security, law enforcement, or other issues of public importance that disclosure of information is necessary.</p>
                        <p>Bullsmart reserves the right to transfer Personal Information of users to another party as a result of business partnership, contractual engagement, merger, acquisition, or sale of all or a portion of Bullsmart is asset to another party, and under such a circumstance, the provisions of this privacy policy will continue to apply unless You are notified otherwise. </p>
                        <p>Bullsmart may use a Third-party technology partnership to provide this Platform and its Services to You, to enable such Services, User information including Profile Information, User Content, behavior, technical and/or transaction information may be shared with such third parties. You hereby agree to allow Bullsmart to share such information with such contracted third parties. </p>
                        <p><strong>Control over user information</strong></p>
                           <p>To access, correction and probability- edit your account information, ask for verification before enabling the information, the request may be rejected in cases where the request risks the privacy of other user or is unlawful</p>
                    
                    </div>
                    {/* <div className="grieveance mt-3">
                        <strong>G. Grievances </strong>
                        <p>If you have any grievances in relation to the Application or its content, you may send a notice to Grievance Redressal Officer at the below-mentioned email and address. </p>
                        <strong>Details of Grievance officer </strong>
                        <p>Name: Ms. SUBHRA SIMANTINEE </p>
                        <address>Address: Ashoka Fortune, NO 3/1-11ST Main, Jakkasandra, Kormangala, Bangalore, Karnataka – 560034</address>
                        <p>Email: compliance@dadostech.in  </p>
                    </div>

                    <div className="strong">
                        <p><strong>Dados Technologies Private Limited (Formerly known as (Wu Quickcash Credit Solutions Private Limited)</strong></p>
                        <p>
                            <strong>CIN: U65100MH2019FTC329281 </strong>
                        </p>
                        <p>

                            <strong>AMFI Registration Number: ARN – 245733 </strong>
                        </p>
                        <p>

                            <strong>Registered Office: No.404, 4th Floor, Kamla Charan, CHS Plot No.178, Jawahar Nagar Road, Goregaon West Mumbai MH 400104 </strong>
                        </p>
                        <p>
                            <strong>Corporate Office:Ashoka Fortune, NO 3/1-11ST Main, Jakkasandra, Kormangala, Bangalore, Karnataka – 560034 </strong>

                        </p>
                        <p>
                            <strong>Disclaimer:  Investments in securities market are subject to market risk, read all the related documents carefully before investing. </strong>
                        </p>
                        <p><strong>Email:</strong>  compliance@dadostech.in </p>
                    </div> */}
            </div>
                </section>
                </>
    )
}
